### ISSUE TITLE
Device Discovery issue

### ISSUE THREAD

**Issue by SirRuggie** [dell/OpenManage-PowerShell-Modules#4]
My devices will only show up when I run a manual discovery from the OME console and check the box that says "Execute all selected protocols when discovering devices. This will increase this discovery task's execution time."

The issue I'm having is that I'm unable to determine how to check the box when running automatically from a script.

**Comment by TrevorSquillario** [comment]
I will include this fix in the next release. I need to backtest this on older versions of OME first. You should just be able to edit the $DiscoveryConfigPayload variable in New-OMEDiscovery.ps1 and add UseAllProfiles: true.

The path will look similar to the following "C:\Users\username\Documents\PowerShell\Modules\DellOpenManage\Public\OME\New-OMEDiscovery.ps1"

```
"UseAllProfiles": true,
"CreateGroup": false,
"TrapDestination": false,
"CommunityString": false
```

https://developer.dell.com/apis/5898/versions/3.7/reference/LatestODataAPIDocumentForOME3_7_v2.json/paths/~1DiscoveryConfigService~1DiscoveryConfigGroups/post

**Comment by SirRuggie** [comment]
That checked the box as I had wanted. Thanks! 

When I run the discovery script, it'll show the discovery job in the Dell OME, but it never updates the device count. 
If I edit that same job and run again, the device count updates... why is that?

**Comment by TrevorSquillario** [comment]
Original issue has been fixed in latest release https://github.com/dell/OpenManage-PowerShell-Modules/releases/tag/2.3.1

Are you using the -Wait parameter. It sounds like the job isn't finished.

**Comment by SirRuggie** [comment]
I've started running the script line by line, but it still will not update the device count. 
Seems like it imports everything over, except updating the device count unless I run it manually from within OME

**Comment by SirRuggie** [comment]
I'm getting the following error when trying to run Connect-OMEServer

`PSMessageDetails      : 
Exception             : System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> 
                        System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
                           at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                           at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean 
                        preserveSyncCtx)
                           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean 
                        preserveSyncCtx)
                           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                           at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
                           at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                           at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                           at System.Net.ConnectStream.WriteHeaders(Boolean async)
                           --- End of inner exception stack trace ---
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-OMEServer, C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\Connect-OMEServer.ps1: line 83
                        at <ScriptBlock>, <No file>: line 12
PipelineIterationInfo : {}






MyCommand             : Invoke-WebRequest
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 83
OffsetInLine          : 25
HistoryId             : 1
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\Connect-OMEServer.ps1
Line                  :         $SessResponse = Invoke-WebRequest -UseBasicParsing -Uri $SessionUrl -Method Post -Body $UserDetails -ContentType $Type
                        
PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\Connect-OMEServer.ps1:83 char:25
                        + ... sResponse = Invoke-WebRequest -UseBasicParsing -Uri $SessionUrl -Meth ...
                        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\Connect-OMEServer.ps1
InvocationName        : Invoke-WebRequest
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 






Status         : TrustFailure
Response       : 
Message        : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Data           : {}
InnerException : System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
                    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean 
                 preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
                    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.ConnectStream.WriteHeaders(Boolean async)
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       : 
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079






Message        : The remote certificate is invalid according to the validation procedure.
Data           : {}
InnerException : 
TargetSite     : Void StartSendAuthResetSignal(System.Net.Security.ProtocolToken, System.Net.AsyncProtocolRequest, System.Exception)
StackTrace     :    at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
                    at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
                    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean 
                 preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
                    at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
                    at System.Net.ConnectStream.WriteHeaders(Boolean async)
HelpLink       : 
Source         : System
HResult        : -2146233087`

**Comment by TrevorSquillario** [comment]
Are you using -IgnoreCertificateWarning

**Comment by SirRuggie** [comment]
ok that fixed that part

**Comment by SirRuggie** [comment]
Now when trying to run New-OMEDiscovery I get the following error. 
I've confirmed the addresses I have it pointing at are up

`PSMessageDetails      : 
Exception             : System.Net.WebException: The remote server returned an error: (400) Bad Request.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : {"error":{"code":"Base.1.0.GeneralError","message":"A general error has occurred. See ExtendedInfo for more 
                        information.","@Message.ExtendedInfo":[{"MessageId":"CGEN1014","RelatedProperties":[],"Message":"Unable to complete the operation because an invalid value is entered for the property  Invalid value 
                        for property: TrapDestination must not be an object or array. .","MessageArgs":["Invalid value for property: TrapDestination must not be an object or 
                        array."],"Severity":"Critical","Resolution":"Enter a valid value for the property and retry the operation. For more information about valid values, see the OpenManage Enterprise-Modular User's Guide 
                        available on the support site."}]}}
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-OMEDiscovery<Process>, C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\New-OMEDiscovery.ps1: line 271
                        at <ScriptBlock>, <No file>: line 28
PipelineIterationInfo : {}






MyCommand             : Invoke-WebRequest
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 271
OffsetInLine          : 33
HistoryId             : 5
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\New-OMEDiscovery.ps1
Line                  :             $DiscoverResponse = Invoke-WebRequest -Uri $DiscoverUrl -UseBasicParsing -Method Post -Body $Payload -Headers $Headers -ContentType $Type
                        
PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\New-OMEDiscovery.ps1:271 char:33
                        + ... rResponse = Invoke-WebRequest -Uri $DiscoverUrl -UseBasicParsing -Met ...
                        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\DellOpenManage\Public\OME\New-OMEDiscovery.ps1
InvocationName        : Invoke-WebRequest
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition : 






Status         : ProtocolError
Response       : System.Net.HttpWebResponse
Message        : The remote server returned an error: (400) Bad Request.
Data           : {}
InnerException : 
TargetSite     : System.Net.WebResponse GetResponse(System.Net.WebRequest)
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
HelpLink       : 
Source         : Microsoft.PowerShell.Commands.Utility
HResult        : -2146233079`

**Comment by TrevorSquillario** [comment]
What version of OME are you using?

**Comment by SirRuggie** [comment]
Version 3.5.0 (Build 60)

**Comment by TrevorSquillario** [comment]
Made a last minute change that slipped through testing. Issue is fixed in the 2.3.2 release.

I'm not able to replicate the device count issue. Might just be a browser cache or page refresh issue.

**Comment by SirRuggie** [comment]
Ok I removed the old module and imported the new one from the PowerShell Gallery, 
I was able to run it and it does show that it completed successfully. 

I have used 2 different browsers and cleared the cache and I am unable to see additional devices.

**Comment by TrevorSquillario** [comment]
If you go to Monitor > Jobs and look at the discovery job, does it give you any logs for the devices?

**Comment by SirRuggie** [comment]
This is what I see:

 Completed
Enabled
OnBoarding job created by discovery job:- 01008391SR02 Discovery
Onboarding_Task
OnBoarding task created by discovery task.
Sep 16, 2021 11:42:09 AM

 Completed
Enabled
01008391SR02 Discovery
Discovery
01008391SR02 Discovery

**Comment by TrevorSquillario** [comment]
If you click on the job then go to View Details on the right. Does it list any devices? If you click on a Device what does the log say on the right?

**Comment by TrevorSquillario** [comment]
Now I'm confused. The UseAllProfiles option is only available in OME 3.7. Do you have a test and a prod instance running different versions?

Edit: I see. Apparently this was available in the API and not in the GUI. Let me do some testing on this. I have a check that limits the UseAllProfiles to 3.7

**Comment by SirRuggie** [comment]
Is there anyway that we can get on the phone? 
I'm and Engineer with Darden

**Comment by TrevorSquillario** [comment]
I got it figured out. New release incoming!

**Comment by TrevorSquillario** [comment]
Just published 2.3.3 which should fix your issue!

**Comment by SirRuggie** [comment]
Nope

**Comment by TrevorSquillario** [comment]
Send me an email Trevor.Squillario@Dell.com, we can hop on a Zoom and take a look

**Comment by SirRuggie** [comment]
So some are being discovered now, but a lot are still being skipped

**Comment by SirRuggie** [comment]
In the new version of OME, how do I check the SNMP Trap boxes via New-OMEDiscovery

**Comment by TrevorSquillario** [comment]
So when you discover these servers using the UI is works as expected? I did a discovery of 44 servers in my lab and all of them showed up. I'm not sure what's going on here...

`-SetTrapDestination` will point the SNMP Trap Destination to your OME instance. Do you want to set the community string as well? I'll have to add that option.

**Comment by SirRuggie** [comment]
So it appears that the OME Server had to be rebooted again after the firmware update, once it rebooted all the devices started to show up and everything appears to be working properly. 

I believe we're good on the SNMP Trap, but I'll let you know if I need anything. 
Thanks again for your help!
